import type { DomainEventType } from '@contracts/events.types';
import { DomainEventTypeEnum } from '@contracts/events.types';
import type { Permission } from '@contracts/users.types';
import { PermissionEnum } from '@contracts/users.types';

export enum ErpModuleEnum {
  BILLING = 'billing',
  CRM = 'crm',
}
export type ErpModule = `${ErpModuleEnum}`;

export const PERMISSION_MODULES: Record<Permission, ErpModule | null> = {
  [PermissionEnum.BILLING_READ]: ErpModuleEnum.BILLING,
  [PermissionEnum.CUSTOMER_WRITE]: ErpModuleEnum.BILLING,
  [PermissionEnum.CUSTOMER_DELETE]: ErpModuleEnum.BILLING,
  [PermissionEnum.CATALOG_WRITE]: ErpModuleEnum.BILLING,
  [PermissionEnum.SUBSCRIPTION_WRITE]: ErpModuleEnum.BILLING,
  [PermissionEnum.INVOICE_WRITE]: ErpModuleEnum.BILLING,
  [PermissionEnum.INVOICE_VOID]: ErpModuleEnum.BILLING,
  [PermissionEnum.CREDIT_NOTE_WRITE]: ErpModuleEnum.BILLING,
  [PermissionEnum.REFUND_WRITE]: ErpModuleEnum.BILLING,
  [PermissionEnum.LEDGER_WRITE]: ErpModuleEnum.BILLING,
  [PermissionEnum.INTEGRATION_WRITE]: ErpModuleEnum.BILLING,
  [PermissionEnum.TEST_CLOCK_WRITE]: ErpModuleEnum.BILLING,
  [PermissionEnum.PORTAL_WRITE]: ErpModuleEnum.BILLING,
  [PermissionEnum.CRM_READ]: ErpModuleEnum.CRM,
  [PermissionEnum.API_KEY_MANAGE]: null,
  [PermissionEnum.USER_MANAGE]: null,
};

export const DOMAIN_EVENT_MODULES: Record<DomainEventType, ErpModule> = {
  [DomainEventTypeEnum.CUSTOMER_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.CUSTOMER_UPDATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.CUSTOMER_DELETED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.PRODUCT_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.PRODUCT_UPDATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.PRICE_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.PRICE_UPDATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.LEDGER_TRANSACTION_POSTED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.LEDGER_TRANSACTION_REVERSED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.SUBSCRIPTION_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.SUBSCRIPTION_UPDATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.SUBSCRIPTION_TRIAL_ENDED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.SUBSCRIPTION_RENEWED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.SUBSCRIPTION_PAUSED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.SUBSCRIPTION_RESUMED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.SUBSCRIPTION_INCOMPLETE_EXPIRED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.SUBSCRIPTION_CANCELED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.TEST_CLOCK_ADVANCED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.METER_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.INVOICE_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.INVOICE_FINALIZED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.INVOICE_PAID]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.INVOICE_VOIDED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.INVOICE_MARKED_UNCOLLECTIBLE]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.INVOICEITEM_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.INVOICEITEM_UPDATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.INVOICEITEM_DELETED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.CREDIT_NOTE_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.CUSTOMER_BALANCE_TRANSACTION_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.CUSTOMER_DISCOUNT_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.CUSTOMER_DISCOUNT_UPDATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.CUSTOMER_DISCOUNT_DELETED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.PAYMENT_INTENT_SUCCEEDED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.PAYMENT_INTENT_FAILED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.REFUND_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.REFUND_UPDATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.CREDIT_NOTE_VOIDED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.PAYOUT_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.PAYOUT_PAID]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.PAYOUT_FAILED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.DISPUTE_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.DISPUTE_UPDATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.DISPUTE_CLOSED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.TAX_RATE_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.TAX_RATE_UPDATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.TAX_ID_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.TAX_ID_UPDATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.TAX_ID_DELETED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.INVOICE_SENT]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.CHECKOUT_SESSION_COMPLETED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.CHECKOUT_SESSION_EXPIRED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.PAYMENT_LINK_CREATED]: ErpModuleEnum.BILLING,
  [DomainEventTypeEnum.PAYMENT_LINK_UPDATED]: ErpModuleEnum.BILLING,
};
