import type { MockPspClient } from '@clients/mock-psp.client';
import type { Env } from '@config/env.schema';
import type { DatabaseClient } from '@database/database.client';
import type { ListenAddress, WorkflowSchedules } from '@plugins/config.plugin';
import type { QueueRegistry } from '@queues/queue-registry';
import type { CreditNoteRepository } from '@repositories/credit-note.repository';
import type { CustomerRepository } from '@repositories/customer.repository';
import type { EntitlementRepository } from '@repositories/entitlement.repository';
import type { IdempotencyKeyRepository } from '@repositories/idempotency-key.repository';
import type { InvoiceRepository } from '@repositories/invoice.repository';
import type { LedgerAccountRepository } from '@repositories/ledger-account.repository';
import type { LedgerTransactionRepository } from '@repositories/ledger-transaction.repository';
import type { MeterRepository } from '@repositories/meter.repository';
import type { MeterEventRepository } from '@repositories/meter-event.repository';
import type { OutboxEventRepository } from '@repositories/outbox-event.repository';
import type { PaymentIntentRepository } from '@repositories/payment-intent.repository';
import type { PriceRepository } from '@repositories/price.repository';
import type { ProductRepository } from '@repositories/product.repository';
import type { RefundRepository } from '@repositories/refund.repository';
import type { ReportingRepository } from '@repositories/reporting.repository';
import type { SubscriptionRepository } from '@repositories/subscription.repository';
import type { TestClockRepository } from '@repositories/test-clock.repository';
import type { WebhookRepository } from '@repositories/webhook.repository';
import type { BillingRunService } from '@services/billing-run.service';
import type { CreditNoteService } from '@services/credit-note.service';
import type { CustomerService } from '@services/customer.service';
import type { DunningService } from '@services/dunning.service';
import type { EntitlementService } from '@services/entitlement.service';
import type { IdempotencyService } from '@services/idempotency.service';
import type { InvoiceService } from '@services/invoice.service';
import type { LedgerService } from '@services/ledger.service';
import type { MeterService } from '@services/meter.service';
import type { MeterEventService } from '@services/meter-event.service';
import type { OutboxService } from '@services/outbox.service';
import type { PaymentService } from '@services/payment.service';
import type { PriceService } from '@services/price.service';
import type { ProductService } from '@services/product.service';
import type { RatingService } from '@services/rating.service';
import type { ReconciliationService } from '@services/reconciliation.service';
import type { RefundService } from '@services/refund.service';
import type { ReportingService } from '@services/reporting.service';
import type { SubscriptionService } from '@services/subscription.service';
import type { TestClockService } from '@services/test-clock.service';
import type { WebhookService } from '@services/webhook.service';
import type { Clock } from '@utils/clock';
import type { RedisKeyFactory } from '@utils/redis-key-factory';
import type { Redis } from 'ioredis';

declare module 'fastify' {
  interface FastifyInstance {
    config: Env;
    clock: Clock;
    database: DatabaseClient;
    redis: Redis;
    redisKeyFactory: RedisKeyFactory;
    serverAddress: ListenAddress;
    workerAddress: ListenAddress;
    workflowSchedules: WorkflowSchedules;
    workerConnection: Redis;
    queuePrefix: string;
    queues: QueueRegistry;
    customerRepository: CustomerRepository;
    idempotencyKeyRepository: IdempotencyKeyRepository;
    entitlementRepository: EntitlementRepository;
    priceRepository: PriceRepository;
    productRepository: ProductRepository;
    subscriptionRepository: SubscriptionRepository;
    testClockRepository: TestClockRepository;
    ledgerAccountRepository: LedgerAccountRepository;
    ledgerTransactionRepository: LedgerTransactionRepository;
    meterEventRepository: MeterEventRepository;
    meterRepository: MeterRepository;
    outboxEventRepository: OutboxEventRepository;
    invoiceRepository: InvoiceRepository;
    creditNoteRepository: CreditNoteRepository;
    paymentIntentRepository: PaymentIntentRepository;
    refundRepository: RefundRepository;
    webhookRepository: WebhookRepository;
    reportingRepository: ReportingRepository;
    customerService: CustomerService;
    idempotencyService: IdempotencyService;
    entitlementService: EntitlementService;
    priceService: PriceService;
    productService: ProductService;
    ratingService: RatingService;
    subscriptionService: SubscriptionService;
    testClockService: TestClockService;
    ledgerService: LedgerService;
    meterEventService: MeterEventService;
    meterService: MeterService;
    outboxService: OutboxService;
    invoiceService: InvoiceService;
    creditNoteService: CreditNoteService;
    billingRunService: BillingRunService;
    paymentService: PaymentService;
    refundService: RefundService;
    dunningService: DunningService;
    webhookService: WebhookService;
    reportingService: ReportingService;
    reconciliationService: ReconciliationService;
    psp: MockPspClient;
  }
}

export {};
