import type { MockPspClient } from '@clients/mock-psp.client';
import type { BillingEnv } from '@config/billing-env.schema';
import type { PartnerPlatform } from '@contracts/customers.types';
import type { BillingSchedules } from '@plugins/billing-config.plugin';
import type { BalanceTransactionRepository } from '@repositories/balance-transaction.repository';
import type { BillingPortalConfigurationRepository } from '@repositories/billing-portal-configuration.repository';
import type { BillingPortalSessionRepository } from '@repositories/billing-portal-session.repository';
import type { CheckoutSessionRepository } from '@repositories/checkout-session.repository';
import type { CollectionAttemptRepository } from '@repositories/collection-attempt.repository';
import type { CouponRepository } from '@repositories/coupon.repository';
import type { CreditNoteRepository } from '@repositories/credit-note.repository';
import type { CustomerRepository } from '@repositories/customer.repository';
import type { CustomerBalanceTransactionRepository } from '@repositories/customer-balance-transaction.repository';
import type { DiscountRepository } from '@repositories/discount.repository';
import type { DisputeRepository } from '@repositories/dispute.repository';
import type { EntitlementRepository } from '@repositories/entitlement.repository';
import type { InvoiceRepository } from '@repositories/invoice.repository';
import type { InvoiceItemRepository } from '@repositories/invoice-item.repository';
import type { LedgerAccountRepository } from '@repositories/ledger-account.repository';
import type { LedgerTransactionRepository } from '@repositories/ledger-transaction.repository';
import type { MeterRepository } from '@repositories/meter.repository';
import type { MeterEventRepository } from '@repositories/meter-event.repository';
import type { NumberSequenceRepository } from '@repositories/number-sequence.repository';
import type { PaymentIntentRepository } from '@repositories/payment-intent.repository';
import type { PaymentLinkRepository } from '@repositories/payment-link.repository';
import type { PaymentMethodRepository } from '@repositories/payment-method.repository';
import type { PayoutRepository } from '@repositories/payout.repository';
import type { PortalSessionRepository } from '@repositories/portal-session.repository';
import type { PortalUserRepository } from '@repositories/portal-user.repository';
import type { PriceRepository } from '@repositories/price.repository';
import type { ProductRepository } from '@repositories/product.repository';
import type { PromotionCodeRepository } from '@repositories/promotion-code.repository';
import type { PspEventRepository } from '@repositories/psp-event.repository';
import type { RefundRepository } from '@repositories/refund.repository';
import type { ReportingRepository } from '@repositories/reporting.repository';
import type { SetupIntentRepository } from '@repositories/setup-intent.repository';
import type { SubscriptionRepository } from '@repositories/subscription.repository';
import type { TaxIdRepository } from '@repositories/tax-id.repository';
import type { TaxRateRepository } from '@repositories/tax-rate.repository';
import type { TestClockRepository } from '@repositories/test-clock.repository';
import type { BalanceService } from '@services/balance.service';
import type { BankTransferService } from '@services/bank-transfer.service';
import type { BillingPortalService } from '@services/billing-portal.service';
import type { BillingRunService } from '@services/billing-run.service';
import type { CheckoutService } from '@services/checkout.service';
import type { ClockService } from '@services/clock.service';
import type { CouponService } from '@services/coupon.service';
import type { CreditNoteService } from '@services/credit-note.service';
import type { CustomerService } from '@services/customer.service';
import type { CustomerBalanceTransactionService } from '@services/customer-balance-transaction.service';
import type { DiscountService } from '@services/discount.service';
import type { DisputeService } from '@services/dispute.service';
import type { DunningService } from '@services/dunning.service';
import type { EntitlementService } from '@services/entitlement.service';
import type { ExpansionService } from '@services/expansion.service';
import type { InvoiceService } from '@services/invoice.service';
import type { InvoiceDocumentService } from '@services/invoice-document.service';
import type { InvoiceItemService } from '@services/invoice-item.service';
import type { InvoiceReminderService } from '@services/invoice-reminder.service';
import type { LedgerService } from '@services/ledger.service';
import type { MeterService } from '@services/meter.service';
import type { MeterEventService } from '@services/meter-event.service';
import type { NotificationService } from '@services/notification.service';
import type { PartnerCollectionService } from '@services/partner-collection.service';
import type { PaymentService } from '@services/payment.service';
import type { PaymentLinkService } from '@services/payment-link.service';
import type { PaymentMethodService } from '@services/payment-method.service';
import type { PayoutService } from '@services/payout.service';
import type { PortalRequestService } from '@services/portal-request.service';
import type { PortalSessionService } from '@services/portal-session.service';
import type { PortalUsageService } from '@services/portal-usage.service';
import type { PortalUserService } from '@services/portal-user.service';
import type { PriceService } from '@services/price.service';
import type { ProductService } from '@services/product.service';
import type { PromotionCodeService } from '@services/promotion-code.service';
import type { RatingService } from '@services/rating.service';
import type { ReconciliationService } from '@services/reconciliation.service';
import type { RefundService } from '@services/refund.service';
import type { ReportingService } from '@services/reporting.service';
import type { SetupIntentService } from '@services/setup-intent.service';
import type { SubscriptionService } from '@services/subscription.service';
import type { SubscriptionItemService } from '@services/subscription-item.service';
import type { TaxService } from '@services/tax.service';
import type { TaxIdService } from '@services/tax-id.service';
import type { TaxRateService } from '@services/tax-rate.service';
import type { TestClockService } from '@services/test-clock.service';
import type { PartnerCollectionProvider } from '@type/partner-collection-provider';
import type { TaxProvider } from '@type/tax-provider';
import type { HostedUrlFactory } from '@utils/hosted-url';

declare module 'fastify' {
  interface FastifyInstance {
    billingConfig: BillingEnv;
    billingSchedules: BillingSchedules;
    customerRepository: CustomerRepository;
    customerBalanceTransactionRepository: CustomerBalanceTransactionRepository;
    entitlementRepository: EntitlementRepository;
    priceRepository: PriceRepository;
    productRepository: ProductRepository;
    subscriptionRepository: SubscriptionRepository;
    testClockRepository: TestClockRepository;
    ledgerAccountRepository: LedgerAccountRepository;
    ledgerTransactionRepository: LedgerTransactionRepository;
    meterEventRepository: MeterEventRepository;
    meterRepository: MeterRepository;
    invoiceRepository: InvoiceRepository;
    invoiceItemRepository: InvoiceItemRepository;
    numberSequenceRepository: NumberSequenceRepository;
    creditNoteRepository: CreditNoteRepository;
    paymentIntentRepository: PaymentIntentRepository;
    paymentMethodRepository: PaymentMethodRepository;
    setupIntentRepository: SetupIntentRepository;
    pspEventRepository: PspEventRepository;
    refundRepository: RefundRepository;
    balanceTransactionRepository: BalanceTransactionRepository;
    payoutRepository: PayoutRepository;
    disputeRepository: DisputeRepository;
    reportingRepository: ReportingRepository;
    couponRepository: CouponRepository;
    promotionCodeRepository: PromotionCodeRepository;
    discountRepository: DiscountRepository;
    taxRateRepository: TaxRateRepository;
    taxIdRepository: TaxIdRepository;
    portalSessionRepository: PortalSessionRepository;
    portalUserRepository: PortalUserRepository;
    billingPortalConfigurationRepository: BillingPortalConfigurationRepository;
    billingPortalSessionRepository: BillingPortalSessionRepository;
    checkoutSessionRepository: CheckoutSessionRepository;
    paymentLinkRepository: PaymentLinkRepository;
    customerService: CustomerService;
    customerBalanceTransactionService: CustomerBalanceTransactionService;
    expansionService: ExpansionService;
    entitlementService: EntitlementService;
    priceService: PriceService;
    productService: ProductService;
    ratingService: RatingService;
    subscriptionService: SubscriptionService;
    subscriptionItemService: SubscriptionItemService;
    clockService: ClockService;
    testClockService: TestClockService;
    ledgerService: LedgerService;
    meterEventService: MeterEventService;
    meterService: MeterService;
    invoiceService: InvoiceService;
    invoiceItemService: InvoiceItemService;
    couponService: CouponService;
    promotionCodeService: PromotionCodeService;
    discountService: DiscountService;
    taxRateService: TaxRateService;
    taxIdService: TaxIdService;
    taxService: TaxService;
    creditNoteService: CreditNoteService;
    billingRunService: BillingRunService;
    notificationService: NotificationService;
    paymentMethodService: PaymentMethodService;
    paymentService: PaymentService;
    setupIntentService: SetupIntentService;
    refundService: RefundService;
    balanceService: BalanceService;
    payoutService: PayoutService;
    disputeService: DisputeService;
    dunningService: DunningService;
    reportingService: ReportingService;
    reconciliationService: ReconciliationService;
    invoiceDocumentService: InvoiceDocumentService;
    bankTransferService: BankTransferService;
    invoiceReminderService: InvoiceReminderService;
    portalSessionService: PortalSessionService;
    portalUserService: PortalUserService;
    portalUsageService: PortalUsageService;
    portalRequestService: PortalRequestService;
    billingPortalService: BillingPortalService;
    paymentLinkService: PaymentLinkService;
    checkoutService: CheckoutService;
    psp: MockPspClient;
    hostedUrlFactory: HostedUrlFactory;
    taxProvider: TaxProvider;
    partnerCollectionProviders: Record<PartnerPlatform, PartnerCollectionProvider>;
    collectionAttemptRepository: CollectionAttemptRepository;
    partnerCollectionService: PartnerCollectionService;
  }
}

export {};
